SELECT TOP (1000) [Id]
      ,[NumeroOS]
      ,[Cliente]
      ,[Contato]
      ,[Endereco]
      ,[DataAbertura]
      ,[DescricaoServico]
      ,[TipoServico]
      ,[DataEntrega]
      ,[FuncionarioId]
      ,[ValorMateriais]
      ,[ValorMaoObra]
      ,[Desconto]
      ,[ValorTotal]
      ,[CondicaoPagamento]
      ,[Observacoes]
  FROM [BlackForgeBD].[dbo].[OrdensServico]
